### ISSUE TITLE
Images broken?

### ISSUE THREAD

**Issue by LourensVeen** [esciencecenter-digital-skills/research-software-support#61] opened 2024-05-15 15:55 UTC
I'm seeing broken image links in the slides at e.g. https://esciencecenter-digital-skills.github.io/research-software-support/modules/licenses/slides. Seems like e.g. https://esciencecenter-digital-skills.github.io/nlesc_style_files/letter-e.svg doesn't exist?

**Comment by raar1** [comment] 2024-05-15 17:14
The problem is that nuxt serves images in its `public/` directory on the root path (`/`) by default. This works fine if you run it locally. However, it seems that on ghpages these are found after the repo prefix.

If you look at <https://esciencecenter-digital-skills.github.io/research-software-support/nlesc_style_files/letter-e.svg> for example, you'll find the white e... It's very annoying.

I'm currently fixing it now (now that I have a working laptop again).

**Comment by raar1** [comment] 2024-05-15 21:46
This was fixed in PR <https://github.com/esciencecenter-digital-skills/NEBULA/pull/40>

Seems to be working on deployed page now

**Closed by raar1** 2024-05-15 21:46 UTC
Labels: platform related
